config/routes.rb
MygovForms::Application.routes.draw do
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  resources :forms, :only => [:index, :show] do
    resources :submissions, :only => [:show, :create]
  end

  get 'forms/:id/start', to: 'forms#start'

  namespace :api, :defaults => {:format => :json} do
    resources :forms, :only => [:index, :show] do
      member do
        post "fill_pdf"
      end
      resources :submissions, :only => [:show, :create]
    end
  end
  root :to => 'forms#index'
end

app/controllers/api/forms_controller.rb
class Api::FormsController < Api::ApiController
  respond_to :json, :xml
  
  def index
    respond_with Form.all
  end
  
  def show
    form = Form.find_by_number(params[:id])
    if form
      respond_with form.as_json.merge(:form_fields => form.form_fields.as_json)
    else
      render :json => {:status => "Error", :message => "Form with id=#{params[:id]} not found"}, :status => 404
    end
  end
    
  def fill_pdf
    form = Form.find_by_number(params[:id])
    unless form
      render :json => {:status => "Error", :message => "Form with number: #{params[:id]} not found."}, :status => 404
    else
      unless form.pdf
        render :json => {:status => "Error", :message => "No PDF associated with that form."}, :status => 404
      else
        begin
          pdf_file = form.pdf.fill_in(params[:data])
          send_data pdf_file, :type => "application/pdf", :filename => File.basename(form.pdf.url)
        rescue Exception => e
          Rails.logger.error(e)
          render :json => {:status => "Error", :message => e.message }, :status => 500
        end
      end
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  def index
    @forms = Form.all
  end

  def show
    @form = Form.find_by_number(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)

    @navigation_items = ActiveSupport::OrderedHash.new
    @navigation_items[:start_content] = {title:"Before You Start", link:"start"}
    @navigation_items[:need_to_know_content] = {title:"What You Need to Know", link:"what_you_need"}
    @navigation_items[:ways_to_apply_content] = {title:"Other Ways to Apply", link:"ways_to_apply"}

  end

  def start
    @form = Form.find_by_number(params[:id])
  end
end

app/helpers/forms_helper.rb
module FormsHelper

  def form_title(form)
    "#{form.title} (#{form.number})"
  end

  def form_input(f, form_field)
    f.input form_field.name.to_sym,
      :as => form_field.formtastic_field_type.to_sym,
      :collection => form_field.options,
      :hint => form_field.description,
      :label => form_field.label || form_field.name.humanize,
      :required => form_field.is_required,
      :input_html => { :title => form_field.tool_tip_text}
  end

  def omb_info(form)
    link_to "Form Approved OMB##{form.omb_control_number} | Expires at #{form.omb_expiration_date}", "http://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=#{form.icr_reference_number}"
  end
end

app/views/forms/index.html.haml
.container
  %h1
    All Forms
  %p.lead
    Select a form
  %ul
    - @forms.each do |form|
      %li
        = link_to form_title(form), form_path(form)

app/views/forms/show.html.haml
.container
  %h1
    = @form.title

  %h4
    = "Form #{@form.number}"

  - if @form.description
    %p
      = @form.description

  %p
    %strong Agency:
    = @form.agency_name
    %br
    %strong Published:
    = @form.published_at.strftime("%a %-d %B %Y")
    %br
    %strong
      Form approved:
    (pull this from reginfo)
    - if @form.omb_expiration_date
      %br
      %strong Exp. Date:
      = @form.omb_expiration_date.strftime("%a %-d %B %Y")

  %p
    .btn-group
      %a{:class=>"btn btn-primary btn-lg", :href=>"#{@form.number}/start"}
        Take me to the form
  %p

  #form-info.tab-content
    %ul{'class'=>'nav nav-tabs', 'data-tabs'=>'tabs'}
      - @navigation_items.each_with_index do |(key,val),index|
        - if @form.send(key)
          %li{:class=> (index == 0 ? "active" : nil)}
            %a{"data-toggle"=>"tab","href"=>"##{val[:link]}"}
              = val[:title]


    - @navigation_items.each_with_index do |(key,val),index|
      - if @form.send(key)
        .tab-pane{:class=>"#{val[:link]} #{'active' if index == 0}", :id=> val[:link]}
          %h3
            = val[:title]
          %p
            = raw @markdown.render(@form.send(key))


  #pra
    %p
      %strong Paperwork Reduction Act
      %br
      This information collection meets the requirements of 44 U.S.C. § 3507, as amended by Section 2 of the Paperwork Reduction Act of 1995. You do not need to answer these questions unless we display a valid Office of Management and Budget control number. We estimate that it will take about 20 minutes to read the instructions, gather the facts, and answer the questions. (time burdern hours * 60 / responses)

app/views/forms/start.html.haml
.container
  %h3
    = form_title(@form)
  %p
    This page will contain information about the form, including background information on what you need to fill it, what you'll need to do, if anything, to provide additional verification, and what to do with the form once it's been filled out.
  %p
    This page will then take the user to an HTML form page that they can fill out with their information.  Or maybe that's just part of this page. I like it all being a part of this page.
  %p
    So down here, we will iterate through the form fields and create input fields to fill out the form.

  %script
    != "var myUsaFormTooltips = #{@form.form_fields.map(&:name).to_json}"

  %p
    = semantic_form_for "data", :url => form_submissions_path(@form) do |f|
      = f.inputs do
        = f.input :form_id, :as => :hidden, :input_html => { :value => @form.id }
        - @form.form_fields.each do |form_field|
          = form_input(f, form_field)

      = f.actions do
        = f.action :submit, :as => :button, :label => "Submit Form"
  - if @form.omb_control_number
    %p#omb
      %small.right
        = omb_info(@form)