config/routes.rb
MygovForms::Application.routes.draw do
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  resources :forms, :only => [:index, :show] do
    resources :submissions, :only => [:show, :create]
  end

  get 'forms/:id/start', to: 'forms#start'

  namespace :api, :defaults => {:format => :json} do
    resources :forms, :only => [:index, :show] do
      member do
        post "fill_pdf"
      end
      resources :submissions, :only => [:show, :create]
    end
  end
  root :to => 'forms#index'
end

app/views/layouts/application.html.haml
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang="en">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "MyUSA Forms"
  = stylesheet_link_tag "application"
  = csrf_meta_tag
%body
  %nav.navbar.navbar-default.navbar.navbar-fixed-top{ role: 'navigation'}
    .navbar-header{role:'banner'}
      %button{'class'=>'navbar-toggle',' data-toggle'=>'collapse', 'data-target'=>'.navbar-collapse', 'type'=>'button', 'title'=>'navbar-toggle'}
        %span{:class=>'icon-bar'}
        %span{:class=>'icon-bar'}
        %span{:class=>'icon-bar'}
      = link_to "MyUSA Forms", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right{role:'menubar'}
        - if user_signed_in?
          %li
            = link_to image_tag('shield.png') + raw('<span>Log Out</span><strong></strong>'), signout_path, id: 'log_out_link', :class => 'right', role: 'menuitem'
        - else
          %li
            = link_to image_tag('shield.png') + raw('<span>Log In</span><strong></strong>'), signin_path, id: 'log_in_link', :class => 'right'


  = yield
  = javascript_include_tag "application"